on:
  issues:
    types:
       - opened
       - labeled
  label:
    types:
        - created
  push:
    branches:
         - main
jobs:
  print_hello:
    runs-on: ubuntu-latest
    steps:
        - run: echo "Hello world"